spring:
  application:
    name: talkify-server

  datasource:
    url: jdbc:mysql://talkify-db.cxy26gic02l1.eu-north-1.rds.amazonaws.com:3306/talkify?useSSL=false
    username: admin
    password: MissRaeen

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

custom:
  jwt:
    secret: 3JrD1GQqLwM+aEbY3sBlxGqKtRzuKTq+5td2DJoW9Fo
