server:
  port: 8080

spring:
  application:
    name: chat-backend

  datasource:
    url: jdbc:mysql://localhost:3306/talkify
    username: root
    password: Miss@786

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
